sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: JYSvB4kViAfAacOOxVupTIRpJDdLPW3MIre4Tkr/n1pjTdG52OePwj+Wy89fKhpuZbhq2B8TwiQwOFRiOs0Qj6Nci4P4LVYNuCPFsLPV7Ruzutl/p7oDzMdhpVury33qVoPTk415PJ2et2X0dvYB3QcZkZoN1vfqqse24qZSTJ8sTohV+X16rvUBDmQUriOIA1IA/Bq3b5Ni9QVJ8uunbK49ab/HXKOaWqHG4gJP+MIE4jENXXs4EnfWM7nJL6WDolJ9eMVZWsNJzW4cZDP8ykJ/mqfcPj+qjrIfPFi1NIfFJi0+Z8QWXv5RraHTjFMKw0djAOdWblplRAa9qBS+pfeKppN6dY8M3fsSCf50QmdD9rh09eM+45T38mVRZQTF7O8lscLViAmSrTVg0XBk78lf+KbohTEfal2fYpKb0TCC1ubMVHd7mtrIKvXBK57gmKg7U0oiH+Brt9b4cmiy0pNdtbbld3Bxo5KUyoq9yzsBAwT7ZF2tz8+JeeU+4SfUVeg5gd2IMKZj45+Q0xvv31DaZV9K8E1kHyHwXBDL61z+AyioYRq4lWcZx37tpB90pEHWMbMD9oFO79EsqJY6Jo9Y871xevE6aq/ZLRWRLgolE7GfGMbGHmPCUVJIhxx8U60DyLVGECId8frc49GE5vKIl63zkU4FoqyI1C1sX+Q=
  - secure: w7apZkXGht/RbLwkXSNx8UqUxXFvb4C1miAxR6soqqOuAR4IfFONVyBC3kZPRPgTx53rvo2L3+7LW++BRGiwxliVQii/g/Sd0Vzc5oeYa3bWb5rW6QrIZtt7qktda62iBJgbWFhJbHRgpCZzpDptrWHaptHavB9MaeW1VbmO0qkvFlDfoqRnEm5UhMD8JQ8YEkt+HtExXvVdCvICeaJ1Vi+7FOBPOpsnW9HBXiU62Jm8O0PR12f1USDtT6SsQkYQ12kSfz/XBn4IAf+4sf/49OZ/HsWK9FWUaxSgecFdpfoPnvcjNJs7eRVPfwrJd1L0KsrKDFxxmIdsym0EEsDyJCl1XoNDUp9/xny4/nmqE1ZKo8QN6yCjpYCkQZXbg1H3R11kApQF2hz6XpFHK5CdQ/evKJObj/r7xdebW3sRLNHlLsO6N0ZWSYhhnQL/Nv7fZb2I4UeMVLlvxXZtlqspKbS/EyBprpuuICbNLZ0LUIrmBIhl5DvMf9XvimS5bTkrbEd/tjFVsP9y8gGo74jPO8j1FqGJvbGMDkApJjU69zofWq3jGXmJSMpBnwbYgGk684G7xBr4uB2/OdwOjB09AgD3w4WPWlx7/t2v8KBdrSiy06kaNbxlJXV7fBW3lUgex2TehqkIfc9Sgc7FuCa8R4hAq3M2S+f5sSpJL3EWYP8=
  - secure: ZHoVSOL2EN6cSILmgbO4EF/Cy8IeIN8EMUBFTKyeHoUxOn/o/EntdDYkmaWq0FuwanTQxoX1OXOhDVL20BrYhJW0FMO5Nk+O0Gwf9jXeSyaxucUHM/BJlDQP4yoC1eAP2pxTGF2AhqNr/k9SfoSuZ1BYYsm1moaiP6T9zabFUYANKS+6iXZhq6PD1EnfRjRTlN98IRjd+Qe7wh+HqXPLWcOviCTFBsqxsSrOaJpG/sF11S3+GyiPFV2gaCt9jOrTmnSgn8LwklcIcsQpGH2IBC4UNH1U7ef24Gzte8pZFSido0LGjStne537zL980/5wkvqVVQU66JL0F668t47mBJaeWTMrOzhTAEHHmRVZ8pyRFn/IH+tC55T0eqiL8fJj63IgA5jJx+HUcLlIKIugV9iw4xhfB0gVAqTm8n6UV0CJh5Jdqw4Am/byVs24qATQOl07Yka+PnjMd1CmXMhbPVUWizBypL9eJ4Azt4qGFRKyXt6FnppXEzx9gRB3X34de5Pbu2QZgdKar/VxdC0iq8TD3GJyr+Ejy4xOUazpfpv9HUoJ1OJe+1JWRIu+eI4B7MM/NSkx20+htQElbztYl50CX1g+yKoa80C3ltkXL431ZxiJCfn2r+3lj4F2uEBQTdpwz7RQXRqDhavxfPfC0AoScymwnaWoGLmVX3h8g5c=
  - secure: 3KmJsopTCJJ5mqULB/f+6Z6lOVBk/XiE5z0uJpiRzyMtwxai6yD2jvp5fN3iHJrYUSVBrKB6/9vF1Vgg+KVPpa+8OTZNqbNmtl450UYth+C4bTzUJTMy1fmgk6mVVqNNsl/03BmEgahBp3VT5WYbRK5PkK1R7o4by4FoYiqEeWogkBiZx1bESFxYfS+ODd//JF9EziBM08/gnSkDHkiT3Rb9M/wOG3wwzlASa0FwcoI0ZmNPUEJagT3Ezd5uyJj73D93oeyjR3ekKpQwtk/mNYWaXjuLbO2mGjj2ciZlPgd/ejgygWqsHnDGdHMChqAGBiCyfRux+wWkSwTr9a2wzazixY+rHK9NcT9Vz/x9h+a0WcJNBNW3mahHLMJsvnHrivN5BVGSZwoRG8jmRCn+E0lkp0Sdq2UTqQtxbffsg4JhymeXAutlKm21FWDxNNRiGgkPdFPcztB1fZc/sl4OmcGhGYZOfP1f8U6ulg6Bg/d8ERVmMJyE/vr257k9fg4Z4O14uWojPPTzFrHroineXrQgsqWA2S3Zh8HZoM63JKqD5GdVs6Fknj86oj8eyDkazpWFA2nrD9eqjSBQR0PpBBBdtefA2iKRG3X69YvrVRV+13mxEJooSEqB8hJsY9bXU6U0I2htRYpFNDesrTguBXmg+ikiGPAYCNDtrYys0kw=
