sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
env:
  global:
  - secure: VX5a6Dsf8UUzWCoK/86IhDVJzK9au8dSdfUNmbLr60QC6eOZ0wdWeWrtOR/1FrcWeAF0z0U19UeOqOwFqe60qBbl8CbAGP+cnSLYURHeUIFKgK82RdfY0SeFzXkT3kLoh8juLB8RT2LtvdeWPnnCtf1D6diHOvpKjxrRn3ZPhQFNenDv5yVlfk3UIfCN3KT9PmeJbSS7J8wpYJTC8az+GzHg06ZLvCw3X664zlq8f2qNcJYEHyuO8JEIFwIg8YPijz/q7vDAK3qAoVsZyVyfTpAKfAgU7AQNqmx0NSWnLCFkRYmyVyVgelXiFoNVN06/xMsNfLgzsNRQz/rXhP5KvpIGQG2NgGWlPpbr6t3NjSZ3giC3Faj95pCmvN8plGuppkkcStYk8ugLiaskdUiXWud0U3B8C7bxH/Ms1eiXu6Cc+xfzMT/u6c7drcrDzOuZshbLK0PAcDR33bgnmknA/kdtADg9vglVvJM4puH+2iIcRxg1vlHXgpxy3GXDRG5BT+PUnYiS4iJN3ZMPy1IEqj8fwooNaAJ7QBIt22gY9QaodrXC1xecQOs7iik6j1Ax5oYnQeO80OHlgNn6nZn5eEUqNBYSVAxWDpEoeDWsmcrb3rQqs4pXkbCv6l2DNiA2UfPgqdeBOC60jSFVz36zkSLLbIgB/j2rW6UrYu1wbBE=
  - secure: WKkVMhyiJ7DeIBG/+sdY1zUq4Jqk7wQqyPbb1+pFH/fYMErSil3BrVxRRrQFLxLc34vCy29FJ9WSRS0KYYTAG7ch9261mVGVZ+g7ecG4WVEgyPrUO+PoN1LuZU3KpjWk2f8PKCMphOC1UH5Oepp3MO1KdKVEtvQsgIrT9P2O4kT/KJSxH5Dg31Dlp0alD8z4zwM+CAoo1mMu+fHObMcjWWgGUwqwbdoGDvEHrAndRRwhfkWMTk9eKq7WPanoYN0zkw9mCpg+77CiikVG2pgHK7cZvdPJVm0rCrzqEVOwAtuUpViniFOt2hXPPjAiCiOp1qbastqX811RrMypeQKy3oOT6GZN3Yqq6jsTlmZvGcY0Sfz6sgEf7V1bV4OiK+f433KOUz048JbYuwEi0iMvFB0AfEZW8CMnHwO3QCm2QGACqPoZDAJn/AH0gyurVuWMabLgV4qrdizSzBaVHaU2gk9U9G3jdB15bvuPieuYbqjf/w615mSNBUvZ0SjFQ/ltsh87GMZr5h+S23EGLh+A+zy+YaD7FWC/xDOBC3i+4eYYtw1P6zfOmB1Z6Jbb/wNYPNlm9a461akWZ9rk+DX3+ZjEkAI0584vcAxgrtaSYWYetrzH+wwOp3+MlXL0iWgET7kVeJwSeW33qP+kR4K7pmNqycIHDuXGZFGtCtBZGwI=
